### PR TITLE
TE-10378: PHP8.1 Support

### PR DESCRIPTION
**Pull request by alexanderM91**
## Ticket:
- https://spryker.atlassian.net/browse/TE-10477

## PR Description

- Support of PHP8.1.
- Support of Alpine 3.14
- Support of Alpine 3.15
- Remove support of Alpine 3.11

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by kj187** [comment]
Just a short question, why is this PR on hold? 
Would be great to get at least PHP version 8.1.3, we need the PHP FPM openmetrics format which is new in 8.1

**Comment by alexanderM91** [comment]
> Just a short question, why is this PR on hold? Would be great to get at least PHP version 8.1.3, we need the PHP FPM openmetrics format which is new in 8.1

Hi @kj187,

we are working with the application preparation for PHP 8.1 support.
As soon as the application is ready, we will continue with an image preparation. 

Note: PHP version will be the latest one on a moment of release.

Thank you.

**Comment by kj187** [comment]
Hey @alexanderM91 

any updates here? 
We need the latest PHP 8.1.x release ;)

**Comment by localheinz** [comment]
@alexanderM91 

I second that, we are building a new application here, looking forward to being able to use PHP 8.1!

**Comment by alexanderM91** [comment]
> @alexanderM91
> 
> I second that, we are building a new application here, looking forward to being able to use PHP 8.1!

Hi, sorry for a long response time. 
I am planning to clarify the application readiness today\tomorrow.

**Comment by localheinz** [comment]
@alexanderM91 

Not a blocker, but of course it would be nice to use all of the new sweet features that PHP 8.1 brings us!

We appreciate your effort, no pressure!

**Comment by alexanderM91** [comment]
Hello, I have small update related to the PHP 8.1 support.
 From the next week we are going to start development and testing process for new images.
 
 Have a great weekend!!!

**Comment by alexanderM91** [comment]
https://github.com/spryker/docker-php/pull/47

**Pull request closed without merging**
